Add fake data file
FatimaAlmashhor/capstone-project-exhale pull request #35
Opened 2020-10-20 09:34 UTC by eng-somaia

2020-10-20 10:25 UTC, MuhannedNoman commented
@eng-somaia Fix the CircleCi

2020-10-20 10:49 UTC, eng-somaia commented
> @eng-somaia Looks like the test has failed. Can you check that out please, and then tag me again once done.

@MuhannedNoman  Passing tests.

2020-10-20 12:00 UTC, MuhannedNoman requested changes

2020-10-20 12:00 UTC, MuhannedNoman commented on fakeData.js
> +        doctorImg: "https://images.all-free-download.com/images/graphiclarge/doctor_work_painting_colored_cartoon_character_sketch_6847622.jpg",
Let's edit this to image only.

2020-10-20 12:00 UTC, MuhannedNoman commented on fakeData.js
> +        specialtyies: "Anxiety, Bipolar Disorder, Depression, General Adult Psychiatry, Personality Disorders",
From the design looks like we will only display one thing. So Let's reflect that her and just pick one thing to add.

2020-10-20 12:00 UTC, MuhannedNoman commented on fakeData.js
> +    {
We need to add date here since it is displayed in the Article page and in home page.

2020-10-20 12:00 UTC, MuhannedNoman commented on fakeData.js
> +const psychiarists = [
Let's add an ID for each element here.

2020-10-20 12:00 UTC, MuhannedNoman commented on fakeData.js
> +const psychiarists = [
Article included.

2020-10-20 12:00 UTC, MuhannedNoman commented
Impressive work here @eng-somaia just left you some comments. Let me know what you think !

2020-10-20 12:06 UTC, MuhannedNoman commented
One last thing let's add a folder in the `src` folder and call it `fake[object]Services.js` ex `fakeDoctorsServices.js`
Inside the file we will only have Doctor's  data. We will use ES6 Export keyword without the word module. Also, add a function and export it call it `get[Object]` that will return the whole data. 
This way we can add and edit stuff in this single file in the future. 
Ex
```
export const doctors = [{},{},{}]

export function getDocotrs() {
     return doctors.filter(d => d)
}

```

2020-10-20 21:18 UTC, eng-somaia commented
@MuhannedNoman Edit all the things you mentioned above. Let me know if there is anything to add or edit.

2020-10-21 08:37 UTC, MuhannedNoman requested changes
LGTM, one thing though. 
Change `fakeData.js` to `fakeArticleService.js` and move the two files into a folder called `services` inside the `src` folder. Once that is implemented feel free to merge.

2020-10-21 09:22 UTC, eng-somaia commented
Done.

2020-10-21 09:23 UTC, merged