Feat : Button component
FatimaAlmashhor/capstone-project-exhale pull request #38
Opened 2020-10-21 17:58 UTC by FatimaAlmashhor

finally

2020-10-22 07:14 UTC, MuhannedNoman requested changes

2020-10-22 07:14 UTC, MuhannedNoman commented on tailwind.config.js
> +        mainPink: '#fbafaf',
We use camel case in naming variables not css classes.Let's use the dash instead of camel case. Also, let's change names to `main-primary`, `main-secondary`...etc

2020-10-22 07:14 UTC, MuhannedNoman commented on src/components/button/Button.jsx
> +};
This is very complicated why are you using useEffect hook !! 
Maybe use something like this. What do you think ?
```
import React from 'react';
const Button = ({ size, varient, type, disabled, text, style }) => {
  const setSize = () => {
    return size === 'lg' ? 'p-4' : 'p-2';
  };
  const setVarient = () => {
    return varient === 'primary' ? 'bg-blue' : 'bg-yellow'; // Or watever you have here.
  };
  return (
    <button type={type} className={`${setSize} ${setVarient}  ${style}`} disabled>
      {text}
    </button>
  );
};
Button.defaultProps = {
  disabled: false,
  size: 'sm',
  type: 'button',
  varient: 'primary',
};
export default Button;
```

2020-10-23 09:00 UTC, FatimaAlmashhor commented
ignore igt commit please @MuhannedNoman  and merge this f*** button

2020-10-23 09:04 UTC, FatimaAlmashhor commented on debug.log
> +[1023/095503.307:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
i do not know why this shown , @MuhannedNoman

2020-10-23 09:06 UTC, FatimaAlmashhor commented on src/components/button/Button.test.js
> +  const tree = renderer.create(<Button text={' '} />).toJSON();
it showed me `console.error node_modules/prop-types/checkPropTypes.js` so i do this to pass it ,should we download enzyme ? @MuhannedNoman

2020-10-23 09:07 UTC, FatimaAlmashhor commented on src/components/button/index.js
> +import React from 'react';
when i do `Button.jsx` and` index.js` have the `export `of the `Button.jsx `the eslint show me error @MuhannedNoman

2020-10-23 09:09 UTC, FatimaAlmashhor commented on src/i18next.js
> -import i18n from 'i18next';
also this one i do not know if it from the rebase of the develop or my bad 3gen work .

2020-11-04 06:35 UTC, closed without merging